Separate ecosystem multisig
ambrosus/airdao-node-contracts pull request #32
Opened 2024-06-10 07:11 UTC by LikoIlya

2024-06-11 07:53 UTC, SvineruS approved these changes

2024-06-11 07:59 UTC, SvineruS requested changes

2024-06-11 07:59 UTC, SvineruS commented on src/contracts/names.ts
> +export enum MultisigVersions {
rename
v2 -> ecosystem
v1 -> general  (?)

2024-06-17 12:28 UTC, LikoIlya commented on src/contracts/names.ts
> +export enum MultisigVersions {
renamed to
`v2` -> `ecosystem`
`v1` -> `common`

2024-07-23 12:05 UTC, merged